name: Email Notification

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
    secrets:
      SMTP_SERVER:
        required: true
      SMTP_PORT:
        required: true
      SMTP_USERNAME:
        required: true
      SMTP_PASSWORD:
        required: true
      NOTIFY_EMAIL_TO:
        required: true
      NOTIFY_EMAIL_FROM:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "CI ${{ github.repository }} (run #${{ github.run_number }}) - ${{ inputs.status }}"
          to: ${{ secrets.NOTIFY_EMAIL_TO }}
          from: ${{ secrets.NOTIFY_EMAIL_FROM }}
          body: "Build result: ${{ inputs.status }}. View run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
